### ISSUE TITLE
Zoom login authentication

### ISSUE THREAD

**Issue by sutantyo** [gaurav1780/comp1010practicalClassMaterial#4]
At the moment zoom authentication doesn't seem to do anything. It would be ideal if we can use domain name authentication as outlined here: https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars#h_5c0df2e1-cfd2-469f-bb4a-c77d7c0cca6f

I have sent a help ticket to Zoom, but I imagine they'd be slow. It seems to be a setting that has to be setup by MQ IT (as the group admin)

**Comment by gaurav1780** [comment]
it's now doing domain authentication
