### ISSUE TITLE
Please update to 1H22-specific pages because these refer to 2H21!

### ISSUE THREAD

**Issue by WilliamAtUni** [gaurav1780/comp1010practicalClassMaterial#9]
https://github.com/gaurav1780/comp1010practicalClassMaterial/blob/4f6009aaaab4a8ef86c71749d4de7d37199fdbdd/week%2005%20-%20classes%20and%20objects%202/practicalClassesObjects2.md?plain=1#L260-L262

https://github.com/gaurav1780/comp1010practicalClassMaterial/blob/4f6009aaaab4a8ef86c71749d4de7d37199fdbdd/week%2005%20-%20classes%20and%20objects%202/practicalClassesObjects2.md?plain=1#L281

**Comment by gaurav1780** [comment]
fixed :)
